version: 8.1.0-R1
parameters:
  chunking:
    semantic_boundary_regex: "[。？！?.!\\n]"
    max_chunk_size: 200
  ri_calibration:
    default_step_latency_ms: 200
  rim_weights:
    salience_multiplier: 1.5

salience_markers:
  - "คะ"
  - "นะ"
  - "จ้ะ"
  - "ครับ"
  - "?"
  - "!"
